const { Router } = require("express");
const router = Router();
const { uploadFile } = require("../File/uploadFile.js");
const { fileNameConflict } = require("../File/fileNameConflict.js");
const { checkSufficientSpace } = require("../File/checkSufficientSpace.js");
const { getUploadProgress } = require("../File/getUploadProgress.js");
const { deleteFile } = require("../File/deleteFile.js");
const { deleteAllFiles } = require("../File/deleteAllFiles.js");
const { getFileList } = require("../File/getFileList.js");
const { renameFile } = require("../File/renameFile.js");
const { getShreddingState } = require("../File/getShreddingState.js");
router.get("/", (req, res) => {
  res.redirect("/app");
});
router.post("/upload", uploadFile);
router.get("/fileNameConflict", fileNameConflict);
router.post("/checkSufficientSpace", checkSufficientSpace);
router.get("/getUploadProgress", getUploadProgress);
router.delete("/delete", deleteFile);
router.delete("/deleteAllFiles", deleteAllFiles);
router.get("/getFileList", getFileList);
router.patch("/renameFile", renameFile);
router.get("/getShreddingState", getShreddingState);
module.exports = router;
